header:
  custom: false
  content: Welcome
search_engines:
  autocomplete: https://ie-dev.uk/autocomplete.php
  google: false
  duckduckgo: true
  reddit: true
columns:
  column0:
    - name: favourite links
      type: title
      value: "Favourite Links"
    - name: Youtube
      type: link
      url: https://www.youtube.com/
    - name: Reddit
      type: link
      url: https://www.reddit.com/
    - name: Amazon
      type: link
      url: https://www.amazon.co.uk/
    - name: Microsoft Rewards
      type: link
      url: https://rewards.bing.com/
  column1:
    - name: development
      type: title
      value: "Development"
    - name: GitHub
      type: link
      url: https://github.com/
    - name: Linode
      type: link
      url: https://cloud.linode.com/
    - name: AWS
      type: link
      url: https://eu-west-2.console.aws.amazon.com/console/home?nc2=h_ct&region=eu-west-2
    - name: Docker Hub
      type: link
      url: https://hub.docker.com/
    - name: Cloudflare
      type: link
      url: https://dash.cloudflare.com/
  column2:
    - name: news
      type: title
      value: "News & Content"
    - name: Floatplane
      type: link
      url: https://www.floatplane.com/channel/linustechtips/home
    - name: EndeavourOS News
      type: link
      url: https://endeavouros.com/news/
    - name: The Verge
      type: link
      url: https://theverge.com/
  column3:
    - name: homelab
      type: title
      value: "Homelab"
    - name: Proxmox
      type: link
      url: https://proxmox.net.local/
    - name: Portainer
      type: link
      url: https://portainer.net.local/
    - name: Pi-hole
      type: link
      url: https://pihole.net.local/admin/
    - name: Home Assistant
      type: link
      url: https://homeassistant.net.local/
  column4:
    - name: email
      type: title
      value: "Email"
    - name: Gmail
      type: link
      url: https://mail.google.com/mail/
    - name: Outlook
      type: link
      url: https://outlook.live.com/mail/
  column5:
    - name: docs
      type: title
      value: "Docs"
    - name: DevDocs
      type: link
      url: https://devdocs.io/
  column6:
    - name: social
      type: title
      value: "Social"
    - name: Mastodon
      type: link
      url: https://mastodonapp.uk/
    - name: Twitter
      type: link
      url: https://twitter.com/home
  column7:
    - name: tools
      type: title
      value: "Tools"
    - name: Monkeytype
      type: link
      url: https://monkeytype.com/
network:
  - name: unifi.net.local
    url: https://unifi.net.local/
  - name: fast.com
    url: https://fast.com/
