header:
  custom: false
  content: Welcome
search_engines:
  autocomplete: https://ie-dev.uk/autocomplete.php
  google: false
  duckduckgo: true
  reddit: true
columns:
  column0:
    - name: favourite links
      type: title
      value: "Favourite Links"
    - name: Youtube
      type: link
      url: https://www.youtube.com/
    - name: Reddit
      type: link
      url: https://www.reddit.com/
    - name: Amazon
      type: link
      url: https://www.amazon.co.uk/
    - name: Microsoft Rewards
      type: link
      url: https://rewards.bing.com/
  column1:
    - name: development
      type: title
      value: "Hosting & Repos"
    - name: GitHub
      type: link
      url: https://github.com/
    - name: Bitbucket
      type: link
      url: https://bitbucket.org/
    - name: Docker Hub
      type: link
      url: https://hub.docker.com/
    - name: Cloudflare
      type: link
      url: https://dash.cloudflare.com/
    - name: AWS
      type: link
      url: https://eu-west-2.console.aws.amazon.com/console/home?nc2=h_ct&region=eu-west-2
    - name: Linode
      type: link
      url: https://cloud.linode.com/
    - name: SpinupWP
      type: link
      url: https://spinupwp.app/dashboard
  column2:
    - name: homelab
      type: title
      value: "Development"
    - name: BugSnag
      type: link
      url: https://app.bugsnag.com/
    - name: ConfigCat
      type: link
      url: https://app.configcat.com/
    - name: MailHog
      type: link
      url: http://localhost:8025/#
    - name: MeiliSearch
      type: link
      url: http://localhost:7700/
    - name: RabbitMQ Management
      type: link
      url: http://localhost:15672/
    - name: RedisInsight
      type: link
      url: http://localhost:8001/
  column3:
    - name: homelab
      type: title
      value: "Homelab"
    - name: Proxmox
      type: link
      url: https://proxmox.ai-ho.me/
    - name: Portainer
      type: link
      url: https://portainer.ai-ho.me/
  column4:
    - name: email
      type: title
      value: "Email"
    - name: Gmail
      type: link
      url: https://mail.google.com/mail/
    - name: Outlook
      type: link
      url: https://outlook.live.com/mail/
  column5:
    - name: news
      type: title
      value: "News & Content"
    - name: Floatplane
      type: link
      url: https://www.floatplane.com/channel/linustechtips/home
    - name: LoFi ATC
      type: link
      url: https://www.lofiatc.com/?icao=KMHT
    - name: EndeavourOS News
      type: link
      url: https://endeavouros.com/news/
    - name: The Verge
      type: link
      url: https://theverge.com/
  column6:
    - name: social
      type: title
      value: "Social"
    - name: Mastodon
      type: link
      url: https://mastodonapp.uk/
    - name: Twitter
      type: link
      url: https://twitter.com/home
  column7:
    - name: docs-tools
      type: title
      value: "Docs & Tools"
    - name: DevDocs
      type: link
      url: https://devdocs.io/
    - name: Monkeytype
      type: link
      url: https://monkeytype.com/
network:
  - name: Unifi
    url: https://unifi.ai-ho.me/
  - name: fast.com
    url: https://fast.com/
