version: '3'
services:
  web-app:
    container_name: apache
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html